name: Build

on: push

jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/@checkout@v2

    - name: Install Modules
      run: npm install

    - name: Unit Tests
      run: npm run test

    - name: Build
      run: npm run build
